### ISSUE TITLE
url amigável

### ISSUE THREAD

**Issue by samuelsilvadev** [ComunidadeProgrameiros/Site-Programeiros#1]
Criar arquivo para configurar url amigáveis

**Comment by meratsunosu** [comment]
Eu já estou resolvendo isso

**Comment by samuelsilvadev** [comment]
Show mano

**Comment by jediazzi** [comment]
O problema ja havia sido resolvido de outra forma anteriormente, e agora como foi refeito rm codeigniter, foi implantado nativamente.
